name: telefunken
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  uuid: ^4.4.2
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flame: ^1.5.0
  cloud_firestore: ^5.6.5
  provider: ^6.1.2
  firebase_core: ^3.12.1
  logging: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  build_test: ^2.2.2
  build_web_compilers: ^4.0.11

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/cards/
    

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
