// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBznoDM8r2Wm5XzN-Aj0r2zeAOBYvumqwk',
    appId: '1:297513093325:web:a4f810255b8bde3fee8184',
    messagingSenderId: '297513093325',
    projectId: 'telefunken-flutter',
    authDomain: 'telefunken-flutter.firebaseapp.com',
    storageBucket: 'telefunken-flutter.firebasestorage.app',
    measurementId: 'G-3PSEQ1R6GK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8zKrwi22e2rhez9DPzY2wl6zSqFnCXSQ',
    appId: '1:297513093325:android:884acf40b238c30dee8184',
    messagingSenderId: '297513093325',
    projectId: 'telefunken-flutter',
    storageBucket: 'telefunken-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALBJgZaa23pf9TrdYsdEi-GY467rpHs50',
    appId: '1:297513093325:ios:c0bfe0af3c890d30ee8184',
    messagingSenderId: '297513093325',
    projectId: 'telefunken-flutter',
    storageBucket: 'telefunken-flutter.firebasestorage.app',
    iosBundleId: 'com.example.telefunken',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALBJgZaa23pf9TrdYsdEi-GY467rpHs50',
    appId: '1:297513093325:ios:c0bfe0af3c890d30ee8184',
    messagingSenderId: '297513093325',
    projectId: 'telefunken-flutter',
    storageBucket: 'telefunken-flutter.firebasestorage.app',
    iosBundleId: 'com.example.telefunken',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBznoDM8r2Wm5XzN-Aj0r2zeAOBYvumqwk',
    appId: '1:297513093325:web:a762797327cf8004ee8184',
    messagingSenderId: '297513093325',
    projectId: 'telefunken-flutter',
    authDomain: 'telefunken-flutter.firebaseapp.com',
    storageBucket: 'telefunken-flutter.firebasestorage.app',
    measurementId: 'G-WSZB0XFC5W',
  );

}